### ISSUE TITLE
Missing definition associatedParty element in PlinianCore AbstractModel File

### ISSUE THREAD

**Issue by matmontal** [tdwg/PlinianCore#10]
In the PlinianCore_AbstractModel_v3.2.2.xsd file, the definition of the associatedParty element can not be found. Only the reference of the element is made, it is not indicated what type it is or if it is defined in another profile.

Reviewing the profiles indicated above, the associatedParty element is defined in the "eml-gbif-profile", which is imported by eml.xsd.

Could you tell me if this case is correct or not? If what I am indicating is correct, could I be notified if the change would be made?

Regards,

Mtr. Mat Max Montalvo Martinez

**Comment by PacoPando** [comment]
Hi Mat,

"the associatedParty element is defined in the "eml-gbif-profile", which is imported by eml.xsd."

That is correct

Its type is  "agentWithRoleType"

![associatedparty](https://user-images.githubusercontent.com/7556279/34245099-c207ca32-e628-11e7-95d7-30489f433336.jpg)

My validator renders "PlinianCore_AbstractModel_v3.2.2.xsd" as valid, and I do not see if and how I have to change this file. Assistance on how to improve this xsd is welcome.

Regarding its definition, in the following document you can find it:
http://www.gbif.jp/v2/pdf/gbif_metadata_profile_guide_en_v1.pdf 

There is refers to:
http://knb.ecoinformatics.org/software/eml/eml-2.1.0/emlresource.html#associatedParty
...now obsolete, but with a little digging you get to:

https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-resource.html

where associatedParty is defined

**Comment by matmontal** [comment]
Hi Paco!

thanks for your prompt response!

I would think that the associatedParty element should follow the same definition as the AncillaryData property. Something similar to the following definition found in the PlinianCore_AbstractModel_v3.2.1.xsd.

Example:
<xs:element name="AncillaryData" type="**eol**:dataObjectBaseType">

because if we analyze it, at the time of referencing the associatedParty element, there is no instruction that indicates to me, that this is referencing the file imported by eml.xsd. Therefore, I have no way to get to the place where it is defined.

Regards.
