### ISSUE TITLE
Different name format element Use-Value

### ISSUE THREAD

**Issue by camiplata** [tdwg/PlinianCore#17]
The name of the element Use-Value has a format that does not match the one of the other elements

https://github.com/tdwg/PlinianCore/wiki/PlinianCore_Terms_3#Use-Value

**Comment by PacoPando** [comment]
Terms in UsesClass (https://github.com/tdwg/PlinianCore/wiki/UsesClass ) are borrowed from http://www.kew.org/tdwguses/rptLevel1_2States.htm. One of these terms is "value". "value" is a reserved word in many programmatic environments, so in this particular case the original term name is changed for  compatibility purposes
