### ISSUE TITLE
Inconsistencies between the use of types and classes

### ISSUE THREAD

**Issue by camiplata** [tdwg/PlinianCore#18]
This happens in several classes/types

<img width="1031" alt="Captura de Pantalla 2021-04-15 a la(s) 3 50 04 p  m" src="https://user-images.githubusercontent.com/5700527/114936794-84cbbd00-9e02-11eb-9119-bb58e5adcf3f.png">

**Comment by PacoPando** [comment]
The "***Class" pages are obsolete and deprecated; they may still be found by search engines, but they are replaced by teh corresponding "***Type" pages, for instance in the example above: https://github.com/tdwg/PlinianCore/wiki/LifeFormType. We will check if there are links that need to be updated

**Comment by PacoPando** [comment]
Issue a addressed, solved and closed
