### ISSUE TITLE
Inconsistencies of the documentation of MiscDetails between sections

### ISSUE THREAD

**Issue by camiplata** [tdwg/PlinianCore#19]
It is also not clear the use of this class and how to use the atomized and unestructured forms

Inside the class
<img width="859" alt="Captura de Pantalla 2021-04-15 a la(s) 4 05 35 p  m" src="https://user-images.githubusercontent.com/5700527/114938555-da08ce00-9e04-11eb-9f6c-641e21faefe8.png">

The atomized versión is missing at the general elements list:
<img width="1080" alt="Captura de Pantalla 2021-04-15 a la(s) 4 05 50 p  m" src="https://user-images.githubusercontent.com/5700527/114938627-f442ac00-9e04-11eb-8ab3-e35ab26eba04.png">

**Comment by PacoPando** [comment]
I think it is fixed now: https://github.com/tdwg/PlinianCore/wiki/MiscDetailType
