### ISSUE TITLE
Is there an RDF/OWL representation of PliC?

### ISSUE THREAD

**Issue by frmichel** [tdwg/PlinianCore#22]
For folks from the SW community, working with the XSDs is quite uneasy. An RDF/OWL representation would be very welcome.

**Comment by GMartSag** [comment]
We agree. The CrossNature project has provided a Turtle format RDF representation of the Plinian Core model, specifically tailored for the EIDOS database (available at https://datos.gob.es/es/catalogo/e05068001-base-de-datos-eidos). The Turtle file was created in 2019 and corresponds to the deprecated version of the abstract model v.3.2.2 (the current version being v.3.2.2.7). 
In line with the recommendation, a folder has been created on GitHub (https://github.com/tdwg/PlinianCore/tree/master/RDF-OWL%20representation) where this file (divided into three partitions) has been included with the aim of updating and completing the version.

**Comment by frmichel** [comment]
Hi @GMartSag, ok good to have it on the repo. We'll try to work on the update during the CESP project.

**Comment by GMartSag** [comment]
Hi @frmichel! We'll make sure to get started on it during the CESP. Thanks for everyone's input and collaboration.
