### ISSUE TITLE
Is PlinianCore ratified by TDWG?

### ISSUE THREAD

**Issue by ManonGros** [tdwg/PlinianCore#24]
Hello, I am trying to figure out if PlinianCore is now officially approved by the TWDG executive committee. I can see from here: https://github.com/tdwg/PlinianCore#latest-developments-and-current-status-2022 that it was about to be submitted in 2021. Where can I find out more?
Thanks!

**Comment by GMartSag** [comment]
Apologies for the delay in responding. The required documentation was submitted to the TDWG Secretary last month (January 2024). We are currently waiting for the Executive Committee's decision (typically, it takes about 30 days). Following the path towards ratification of a TDWG standard, if the response obtained is positive, the Executive Committee will appoint a Review Manager, and the process will move to the Public Review phase (more information about the TDWG process at https://www.tdwg.org/about/process/).
