### ISSUE TITLE
Review links in the wiki and update to https://github.com/tdwg/PlinianCore/wiki

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/PlinianCore#4]
The wiki contains (absolute) links to https://github.com/PlinianCore/Documentation/wiki, rather than the new https://github.com/tdwg/PlinianCore/wiki (e.g. the "About Plinian Core" link at https://github.com/tdwg/PlinianCore/wiki). These should be reviewed and updated.

Some pages also link to the sources repo, e.g.:

> https://raw.githubusercontent.com/PlinianCore/Sources/master/xsd/abstract%20models/stable%20version/PlinianCore_AbstractModel_v3.2.1.xsd

That should be updated as well.

**Comment by nestorjal** [comment]
I've updated the Wiki links from https://github.com/PlinianCore/Documentation/wiki/ to https://github.com/tdwg/PlinianCore/wiki/

[cd108f4](https://github.com/tdwg/PlinianCore/wiki/Home/cd108f4020746503825381b0d119a4bcfdbf0916)

**Comment by nestorjal** [comment]
I've updated the Wiki links from https://raw.githubusercontent.com/PlinianCore/Sources/master to https://raw.githubusercontent.com/tdwg/PlinianCore/master/

[35e139c](https://github.com/tdwg/PlinianCore/wiki/Home/35e139cc75f51f3c2cc82ab0052415261768c2e8)

**Comment by peterdesmet** [comment]
Nice! 👍
