### ISSUE TITLE
Create an overview that points out the relationship between PlinianCore and related standards (SDD, Delta, Speciesprofile,..)

### ISSUE THREAD

**Issue by wouteraddink** [tdwg/PlinianCore#9]

**Comment by PacoPando** [comment]
Excellent... I 'll be on it soon

**Comment by PacoPando** [comment]
I started today with this exercise and hit the first bump; The  SDD primer is not available... as Gail pointed out some time ago: https://github.com/tdwg/sdd/issues/4 . Does anyone know where to to find it? (and solve Gail's issue).

**Comment by wouteraddink** [comment]
I think I found it back: https://github.com/tdwg/wiki-archive/blob/master/twiki/data/SDD/Primer/SddIntroduction.txt

**Comment by PacoPando** [comment]
The overview was created and presented at TDWG 2018. It is available at:
[https://biss.pensoft.net/article/25869/list/19/](https://biss.pensoft.net/article/25869/list/19/)
(abstract)

[https://biss.pensoft.net/getfile.php?file_id=231807](https://biss.pensoft.net/getfile.php?file_id=231807)
(presentation)
